# Generated by Django 5.0.6 on 2024-06-13 06:44

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Locations',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('location', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField()),
                ('temperature', models.DecimalField(decimal_places=2, max_digits=3)),
                ('humidity', models.DecimalField(decimal_places=2, max_digits=3)),
                ('description', models.CharField(max_length=255)),
            ],
        ),
    ]
